### ISSUE TITLE
Don't use `session-bus` permission

### ISSUE THREAD

**Issue by hfiguiere** [flathub/app.moosync.moosync#1]
Don't use `session-bus` permission

See https://github.com/flathub/app.moosync.moosync/commit/e1d77ec950adf2ce71a099ea5281fd1fb0b62135#commitcomment-75703326

**Comment by Ovenoboyo** [comment]
Electron at this time doesn't provide any control over the namespace of MPRIS. The default MPRIS namespace is ```org.mpris.MediaPlayer2.chromium.instance${number}``` which is not the same for all systems I believe.

Is there any solution for this other than manually implementing MPRIS spec?

**Comment by rusty-snake** [comment]
`--own-name=org.mpris.MediaPlayer2.chromium.*` is at least more secure than `--socket=session-bus`.

**Comment by Ovenoboyo** [comment]
Oh ok. If org.mpris.MediaPlayer2.chromium.* sounds acceptable then thats great

**Comment by rusty-snake** [comment]
FWIW: https://github.com/flathub/io.freetubeapp.FreeTube/pull/65/commits/768225c8a47d6b1d4bfba1fffa1878cc2d3ee50d (this PR: https://github.com/flathub/io.freetubeapp.FreeTube/pull/65)

**Comment by Ovenoboyo** [comment]
Thanks a lot
